LABELS = {
    "en": {
        "title": "Shot Form Coach",
        "review": "Movement review",
        "reference": "Personal comparator",
        "teaching": "Teaching cue - schematic",
        "release": "Release interval",
        "extension": "Extension candidate",
        "unknown": "Not assessable",
        "projection": "Image-projection measurements",
        "hypothesis": "Practice hypothesis - check with a matched retest",
        "observation": "Visible movement change",
        "difference": "Difference from the selected comparator",
        "rhythm": "Loading-to-release timing",
        "repeatable_finish": "After release, let your fingertips continue toward the chosen target with a relaxed finish. Review a set from a comfortable distance.",
        "coordinated_rise": "Try a comfortable, continuous rise and ball lift, then compare attempts at the same location.",
        "limits": "Measurements describe the visible projection. A difference does not establish a fault or the cause of a miss.",
        "no_ref": "No motion comparator selected",
        "schematic_note": "Original schematic; no measured Curry motion",
        "wrist_height_early": "Early wrist height",
        "wrist_height_late": "Later wrist height",
        "arm_lowering": "Wrist-height change",
        "elbow_extension_change": "Projected elbow change",
        "loading_to_release": "Loading-to-release timing",
        "torso_lengths": "body-reference lengths",
        "degrees_projection": "projected degrees",
        "milliseconds": "ms",
        "release_unknown": "Release contact is not sufficiently visible. The interval can be corrected.",
        "track_gaps": "Required body points are not visible in enough frames.",
        "post_context_short": "The clip lacks enough later follow-through context.",
        "handedness_uncertain": "The shooting side needs review.",
        "handedness_mismatch": "The shooting hands differ.",
        "ball_not_visible": "Ball tracking is incomplete.",
        "context_mismatch": "Shot type or camera view differs.",
        "view_unverified": "Matching camera view has not been established.",
        "reference_unanalyzed": "Analyze the comparator before numerical comparison.",
        "phase_note": "Phase anchors are estimates unless reviewed; source timestamps remain traceable.",
        "source": "Source",
        "clip": "Clip",
        "revision": "Revision",
        "supported": "Available",
    },
    "zh": {
        "title": "投篮动作复盘",
        "review": "动作观察",
        "reference": "个人比较样本",
        "teaching": "教学目标示意",
        "release": "离手区间",
        "extension": "伸展高点候选",
        "unknown": "当前无法判断",
        "projection": "画面投影指标",
        "hypothesis": "训练假设：通过同条件重拍检验",
        "observation": "可见的动作变化",
        "difference": "与所选样本的差异",
        "rhythm": "下沉低点到离手的时序",
        "repeatable_finish": "离手后让指尖继续指向选定目标，保持自然放松的结束动作；做一组舒适距离投篮后再回看。",
        "coordinated_rise": "尝试自然连贯的起身和举球，再比较相同位置的多次动作。",
        "limits": "指标描述可见的画面投影。差异本身不证明技术错误或未进原因。",
        "no_ref": "尚未选择运动参照",
        "schematic_note": "原创教学示意，非库里实测动作",
        "wrist_height_early": "离手后较早的腕部高度",
        "wrist_height_late": "离手后较晚的腕部高度",
        "arm_lowering": "腕部高度变化",
        "elbow_extension_change": "投影肘部角度变化",
        "loading_to_release": "下沉低点到离手时长",
        "torso_lengths": "身体参考长度",
        "degrees_projection": "画面投影度数",
        "milliseconds": "毫秒",
        "release_unknown": "球与手的接触证据不足，可以修正离手区间。",
        "track_gaps": "所需身体点在足够多的帧中不可见。",
        "post_context_short": "片段缺少足够的后续随挥。",
        "handedness_uncertain": "出手侧需要复核。",
        "handedness_mismatch": "出手侧不同。",
        "ball_not_visible": "球的跟踪不完整。",
        "context_mismatch": "投篮类型或视角不同。",
        "view_unverified": "尚未确认两个片段的视角可比。",
        "reference_unanalyzed": "先分析参照，再比较数值。",
        "phase_note": "未复核阶段保留估计状态，所有时刻可追溯到原帧。",
        "source": "源时间",
        "clip": "片段",
        "revision": "版本",
        "supported": "可用",
    },
}


def labels(locale):
    return LABELS.get(locale, LABELS["en"])
